package com.wedding.backend.util.message;

public class MessageUtil {
    public static final String MSG_PROCESS_SUCCESS = "Xử lý yêu cầu thành công.";
    public static final String MSG_ROLE_NOT_FOUND = "Vai trò không tồn tại !";
    public static final String MSG_ROLE_EXITED = "Vai trò tồn tại !";
    public static final String MSG_OTP_CODE_INCORRECT = "Rất tiếc! Mã OTP của bạn không chính xác.";
    public static final String MSG_OTP_CODE_CORRECT = "Mã OTP của bạn chính xác.";
    public static final String MSG_ADD_SUCCESS = "Thêm mới thành công !";
    public static final String MSG_UPDATE_SUCCESS = "Cập nhật thành công !";
    public static final String MSG_DELETE_SUCCESS = "Xóa thành công !";
    public static final String MSG_SYSTEM_ERROR = "Lỗi hệ thống vui lòng thử lại sau !";
    public static final String MSG_REGISTER_FAIL = "Rất tiếc! Đăng ký tài khoản thất bại !";
    public static final String MSG_REGISTER_SUCCESS = "Đăng ký tài khoản thành công.";
    public static final String MSG_AUTHENTICATION_FAIL = "Đăng nhập không thành công. Vui lòng kiểm tra số điện thoại hoặc mật khẩu.";
    public static final String MSG_USER_BY_TOKEN_NOT_FOUND = "Không thể tìm thấy người dùng với token !";
    public static final String MSG_USER_BY_ID_NOT_FOUND = "Không thể tìm thấy người dùng với id !";
    public static final String MSG_PHONE_NUMBER_IS_EXITED = "Số điện thoại đã tồn tại. Vui lòng nhập số điện thoại mới";
    public static final String MSG_EMAIL_IS_EXITED = "Email đã tồn tại. Vui lòng nhập email mới";
    public static final String MSG_PHONE_NUMBER_FORMAT_INVALID = "Số điện thoại không đúng định dạng.";
    public static final String MSG_PHONE_NUMBER_NOT_FOUND = "Số điện thoại không đúng. Vui lòng nhập số điện thoại mới";
    public static final String MSG_PHONE_NUMBER_CONFIRM_NOT_VALID = "Số điện thoại xác thực không đúng. Vui lòng nhập số điện thoại mới";
    public static final String MSG_UPDATE_PROFILE_IMAGE_SUCCESS = "Cập nhật hình ảnh thành công.";
    public static final String MSG_SEND_OTP_DELIVERED = "Gửi mã OTP thành công.";
    public static final String MSG_SEND_OTP_FAILED = "Rất tiếc! Không thể gửi mã OTP.";
    public static final String MSG_SERVICE_NOT_FOUND = "Dịch vụ không tồn tại !";
    public static final String MSG_SERVICE_TYPE_NOT_FOUND = "Loại dịch vụ không tồn tại !";
    public static final String MSG_WISHLIST_ITEM_EXITED = "Danh sách yêu thích đã tồn tại dịch vụ";
    public static final String MSG_OK = "Thành công";
    public static final String MSG_PROCESS_TRANSACTION_PAYMENT_FAIL = "Xin lỗi, giao dịch thanh toán của bạn không thành công.";
    public static final String MSG_PROCESS_TRANSACTION_PAYMENT_SUCCESS = "Cảm ơn bạn, giao dịch thanh toán thành công !";
    public static final String MSG_PAYMENT_NOT_FOUND = "Giao dịch thanh toán không tìm thấy.";
    public static final String MSG_TRANSACTION_SERVICE_SUCCESS_WITH_SMS = "Giao dich thanh toán dịch vụ thành công, Vui lòng kiểm tra SMS để xem chi tiết ";
    public static final String MSG_TRANSACTION_EXTENSION_SERVICE_SUCCESS_WITH_SMS = "Giao dich thanh toán gia hạn dịch vụ thành công, Vui lòng kiểm tra SMS để xem chi tiết ";
    public static final String MSG_TRANSACTION_SERVICE_SUCCESS_WITHOUT_SMS = "Giao dich thanh toán dịch vụ thành công. Lỗi gửi SMS! ";
    public static final String MSG_TRANSACTION_EXTENSION_SERVICE_SUCCESS_WITHOUT_SMS = "Giao dich thanh toán gia hạn dịch vụ thành công. Lỗi gửi SMS! ";
    public static final String MSG_BALANCE_NOT_ENOUGH = "Hiện tại, Số dư của bạn không đủ để thực hiện giao dịch.";
    public static final String MSG_SERVICE_EXISTS = "Dịch vụ tồn tại!";
    public static final String SUPPLIER_NOT_FOUND = "Nhà cung cấp không tồn tại!";
    public static final String MSG_SEND_BOOKING_SUCCESS = "Gửi báo giá thành công";
    public static final String ADD_REPORT_SUCCESS = "Cam on thong tin bao cao dich vu cua ban";
    public static final String MSG_SUCCESS = "Success";
    public static final String UPDATE_STATUS_SERVICE_SUCCESS = "Cap nhat trang thai dich vu thanh cong!";
    public static final String MSG_ID_FORMAT_INVALID = "Mã sai định dạng !";
}
