const path = {
    LAYOUT: "/",
    HOME: "",
    LOGIN: "login",
    INVALID: "*",
    MEMBER: "member",
    TOP_PROVINCE: "tinh-thanh",
    WISHLIST: "danh-sach-yeu-thich",
    PERSONAL: "thong-tin-ca-nhan",
    SUPPLIER: "supplier",
    VERIFY_PHONE: "xac-minh-so-dien-thoai",
    INFORMATION_SUPPLIER: "thong-tin-nha-cung-cap",
    LIST: "danh-sach",
    DETAIL_POST: "chi-tiet-dich-vu",
    DETAIL_POST__PID__TITLE: "chi-tiet-dich-vu/:pid/:title/*",
    DEPOSIT: "nap-tien",
    PAYMENT_RESULT: "payment/status",
    HISTORIES_PAYMENT: "lich-su-thanh-toan",
    MANAGE_DEPOSIT: "quan-ly-nap-tien",
    MANAGE_SERVICE: "quan-ly-dich-vu",
    CREATE_SERVICE: "tao-moi-dich-vu",
    PRICING: "bang-gia-goi",
    SUPPLIER_DETAIL__SID__NAME: "chi-tiet-nha-cung-cap/:supplierId/:supplierName",

    ADMIN: "admin",
    DASHBOARD: "dashboard",
    MANAGE_SERVICES_ALL: "quan-ly-tat-ca-tin-dang",
    MANAGE_USER: "quan-ly-thanh-vien",
    MANAGE_PRICING: "quan-ly-bang-gia-dich-vu",
    CREATE_PRICING: "tao-moi-bang-gia-dich-vu",
    MANAGER_PAYMENT: "payment",
    MANAGE_REPORT: "bao-cao-vi-pham",

}
export default path